"""add_email_unique_and_login_logs

Revision ID: 389e8ca13cec
Revises: 0336870d7cc1
Create Date: 2026-04-13 17:06:08.173183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '389e8ca13cec'
down_revision: Union[str, None] = '0336870d7cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_logs_created_at'), 'login_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_logs_success'), 'login_logs', ['success'], unique=False)
    op.create_index(op.f('ix_login_logs_username'), 'login_logs', ['username'], unique=False)
    op.alter_column('drugs', 'approval_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='批准文号（国药准字）',
               existing_comment='批准文号',
               existing_nullable=True)
    op.alter_column('drugs', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='分类（处方药/OTC）',
               existing_comment='分类',
               existing_nullable=True)
    op.alter_column('inventory_records', 'quantity',
               existing_type=mysql.INTEGER(),
               comment='数量（正数入库/负数出库）',
               existing_comment='数量',
               existing_nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('inventory_records', 'quantity',
               existing_type=mysql.INTEGER(),
               comment='数量',
               existing_comment='数量（正数入库/负数出库）',
               existing_nullable=False)
    op.alter_column('drugs', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='分类',
               existing_comment='分类（处方药/OTC）',
               existing_nullable=True)
    op.alter_column('drugs', 'approval_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='批准文号',
               existing_comment='批准文号（国药准字）',
               existing_nullable=True)
    op.drop_index(op.f('ix_login_logs_username'), table_name='login_logs')
    op.drop_index(op.f('ix_login_logs_success'), table_name='login_logs')
    op.drop_index(op.f('ix_login_logs_created_at'), table_name='login_logs')
    op.drop_table('login_logs')
    # ### end Alembic commands ###
